name: Build Blog Actions Demo
on: [push]
jobs:
  Build-Blog-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    steps:
      - run: echo "å¼€å§‹ç¼–è¯‘ ${{ github.event_name }}"
      - run: echo "å½“å‰é€šè¿‡GitHubè¿è¡Œåœ¨ ${{ runner.os }}!"
      - run: echo "ä¸»è¦å¯¹ ${{ github.repository }} çš„ ${{ github.ref }} åˆ†æ”¯"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "ğŸ’¡ ${{ github.repository }} å·²ç»å¤åˆ¶ä¸‹æ¥äº†"
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm install
      - run: npm run build --if-present